backend:
  name: github
  repo: eostrom/oncoming-gatsby
  branch: feature/netlify-cms
publish_mode: editorial_workflow
media_folder: 'static/uploads'
public_folder: '/uploads'
collections:
  - name: 'people'
    label: 'People'
    folder: 'src/people'
    create: true
    fields:
      - {label: 'Name', name: 'name', widget: 'string'}
      - {label: 'Picture', name: 'picture', widget: 'image'}